### ISSUE TITLE
Improvement: save commands in a database

### ISSUE THREAD

**Issue by elkinaguas** [elkinaguas/clir#14]
I've thought about using a SQLite DB for this.

**Comment by croketillo** [comment]
In my opinión more simple ever better. I like how  its now…

**Comment by elkinaguas** [comment]
I agree, I would like it to stay simple, but at the same time I want to add some complex functionalities that work better with a DB. For the moment, I'll see how I can implement the new features using json files only.

**Comment by elkinaguas** [comment]
I'm reopening this issue. Future features will require the use of a db, using only JSON files won't do the trick. I'm going for SQLite, a simple relational database.

I'll add a feature to export commands to a JSON file. This will facilitate portability and readability outside Clir.

**Comment by elkinaguas** [comment]
Done! That took time.

I'm planning to add an import and export function #33.
